#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    #- $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=256m"
before_script:
  - sudo keytool -import -alias sonar -keystore $JAVA_HOME/jre/lib/security/cacerts -file sonar_cert.pem -storepass changeit -noprompt
script:
  - ./gradlew build jacocoTestReport sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: ./gradlew -Prelease.customUsername=$GIT_USER -Prelease.customPassword=$GIT_PASSWORD -Prelease.disableChecks -Prelease.pushTagsOnly release bintrayUpload
  on:
    branch: master
    jdk: oraclejdk8
addons:
  hosts:
    - travis-ci
