site_name: Mstor
site_url: https://www.mstor.org
theme:
  name: material
  favicon: images/cherry.png
  logo: images/mnode_logo.png
repo_url: https://github.com/micronode/mstor
repo_name: micronode/mstor
extra:
  analytics:
    provider: google
    property: UA-402774-13
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/micronode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Overview:
    - Introduction: index.md
    - Javamail: javamail.md
  - References:
    - Resources: resources.md
  - FAQ: faq.md
