


From - Mon June 02 12:00:00 1997
X-Mozilla-Status: a000
Message-ID: <333DB463.23F1@medicineman.com>
Date: Mon, 02 Jun 1997 12:00:00 -0800
From: Mark Lyon Testing <marklyon@gmail.com>
Reply-To: marklyon@gmail.com
Organization: Mark Lyon's Gmail Loader
X-Mailer: Mozilla 4.05 (Win95; I)
MIME-Version: 1.0
To: GML User
Subject: Test Message 2
X-Priority: 3 (Normal)
Content-Type: multipart/related; boundary="----------2E29447026B50"


------------2E29447026B50
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset=us-ascii

<HTML>
<HEAD>
<TITLE>Navigation</TITLE>
<META NAME="Author" CONTENT="Medicineman Media Solutions -- info@medicineman.com">

<SCRIPT LANGUAGE="JavaScript">


detailText = new Array("Alpha Industrial Indices invests in the industrial sectors of the three major indices. Performance is up, with returns improving in each of the last three years.",
                   "BlueNote Equities is a specialty fund, investing mainly in music industry stocks. The fund has outperformed nearly every index in the past three years.",
                   "The Equitas Global Growth fund invests in emerging markets around the world. Japan, Germany and Italy are areas of concentration",
                   "Trilogy Equity Fund seeks rapid growth through investments in three areas: High Tech, Entertainment,and Health Care stocks.",
                   "Trilogy Socially Conscious Fund buys companies with a record of giving. Ignored are companies doing business with governments with human rights violations.");

function display_off(num) {
}

function display_on(num) {
  document.forms[0].detail.value = detailText[num];
}

document.bgColor="#ffffff"

</SCRIPT>
</HEAD>
<BODY BGCOLOR="#ffffff">
<H3><font color="#668266" face="Helvetica, Arial">Airius Airway's 401k Contributions Worksheet (Sample Only)</font></H3>
<hr>
<script>
function doForm()
{
   theMsg="This is an example of how your company can use the rich HTML e-mail capabilities of Messenger to process work-flow applications. If this were an actual application your 401-k selections could be automatically processed."
   alert(theMsg)
}
</script>

<FORM action="" method="POST" onSubmit="doForm();return false">

 <TABLE BORDER=0 CELLPADDING=1 WIDTH="100%">
   <TR>
      <TD WIDTH="220">
         <H5><FONT COLOR="#668266">Employee Name</FONT></H5>
      </TD><TD WIDTH="153">
         <H5><CENTER><FONT COLOR="#668266">Social Security
         Number</FONT></CENTER></H5>
      </TD></TR>
   <TR>
      <TD WIDTH="220">
          <INPUT TYPE="text" NAME="name" VALUE="" SIZE=30>
      </TD><TD WIDTH="153">
          <CENTER><INPUT TYPE="text" NAME="name" VALUE=""
         SIZE=3>-<INPUT TYPE="text" NAME="name" VALUE=""
         SIZE=2>-<INPUT TYPE="text" NAME="name" VALUE="" SIZE=4>
         </CENTER>
      </TD></TR>
</TABLE>

 <TABLE BORDER=0 CELLPADDING=1>
   <TR>
      <TD WIDTH="262">
         <H5><FONT COLOR="#668266">Fund Options</FONT></H5>
      </TD><TD WIDTH="155">
         <H5><CENTER><FONT COLOR="#668266">Monthly
         Contribution</FONT></CENTER></H5>
      </TD></TR>
   <TR>
      <TD WIDTH="262">
        <A HREF onClick="return false"; onMouseOver="display_on(0); return true" onMouseOut="display_off(0)"><IMG SRC="cid:part1.333DB463.2F3A@medicineman.com" NAME="alpha" WIDTH=157 HEIGHT=14 BORDER=0></A>

      </TD><TD WIDTH="155">
          <CENTER>%<INPUT TYPE="text" NAME="name" VALUE="" SIZE=5>
         </CENTER>
      </TD></TR>
   <TR>
      <TD WIDTH="262">
          <A HREF onClick="return false"; onMouseOver="display_on(1); return true" onMouseOut="display_off(1)"><IMG SRC="cid:part2.333DB463.2F3A@medicineman.com" NAME="blue" WIDTH=119 HEIGHT=14 BORDER=0></A>

      </TD><TD WIDTH="155">
          <CENTER>%<INPUT TYPE="text" NAME="name" VALUE="" SIZE=5>
         </CENTER>
      </TD></TR>
   <TR>
      <TD WIDTH="262">
         <A HREF onClick="return false"; onMouseOver="display_on(2); return true" onMouseOut="display_off(2)"><IMG SRC="cid:part3.333DB463.2F3A@medicineman.com" NAME="equitas" WIDTH=148 HEIGHT=14 BORDER=0></A>

      </TD><TD WIDTH="155">
          <CENTER>%<INPUT TYPE="text" NAME="name" VALUE="" SIZE=5>
         </CENTER>
      </TD></TR>
   <TR>
      <TD WIDTH="262">
         <A HREF onClick="return false"; onMouseOver="display_on(3); return true" onMouseOut="display_off(3)"><IMG SRC="cid:part4.333DB463.2F3A@medicineman.com" NAME="trilogye" WIDTH=127 HEIGHT=14 BORDER=0></A>

      </TD><TD WIDTH="155">
          <CENTER>%<INPUT TYPE="text" NAME="name" VALUE="" SIZE=5>
         </CENTER>
      </TD></TR>
   <TR>
      <TD WIDTH="262">
       <A HREF onClick="return false"; onMouseOver="display_on(4); return true" onMouseOut="display_off(4)"><IMG SRC="cid:part5.333DB463.2F3A@medicineman.com" NAME="trilogys" WIDTH=203 HEIGHT=14 BORDER=0></A>

      </TD><TD WIDTH="155">
          <CENTER>%<INPUT TYPE="text" NAME="name" VALUE="" SIZE=5>
         </CENTER>
      </TD></TR>
   <TR>
      <TD COLSPAN=2 WIDTH="417" HEIGHT="61">
      <TEXTAREA NAME="detail" ROWS=4 COLS=45 WRAP=physical SCROLLBAR=false></TEXTAREA>
      </TD></TR>
   <TR>
      <TD COLSPAN=2 WIDTH="417">
          <I><FONT SIZE="-1">After specifying your monthly
         contribution, (You may contribute to as many funds as you
         like) submit this form. You will receive email confirming
         your choices. Airius Contributes $0.50 for every $1.00 you
         contribute. All dollars you contribute are deducted from
         your salary before taxes. </FONT></I>
      </TD></TR>
</TABLE><INPUT TYPE="submit" NAME="name"
VALUE="Submit"><INPUT TYPE="reset" VALUE="Reset">
</FORM>

</BODY>

</HTML>


------------2E29447026B50
Content-ID: part1.333DB463.2F3A@medicineman.com
Content-Transfer-Encoding: base64
Content-Type: image/gif

R0lGODlhnQAOAMQAAP////Ly7+Xl39nZz8zMv7+/r7Kyn6Wlj5mZf42NcICAYHNzUGZmQFlZ
ME1NIEBAEDMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ACwAAAAAnQAOAAAF/yAgDgQhjoRwrqjKvm/pwqtADHSuE4iR2zgWKagDBEoAnq/IPD0gkMKJ
AUHkqNbmCpotIiAM7cnAWLK+YRr6RU0XCVDAWqwrQCGJafW6pwO4TXNiX10rZHlqYGyKTHAQ
AId+OQoQDpV6VgYIPAxZWAidJwQJDAwHAS+AmgOkXWQKCYqaJkoiBgqmqKBgVkoJBrUAAqAM
CSqCemE8BAcMCqhJCwsHccEAB9JmAc0KJiKjxTOWdhBBWABUDw1Peel3VuQMTwupe1SWUAeQ
UFSK52uxGjRQdCfOlycI1gh40sDSAzmMVrSBiA8CPQFQ1hlkNPCOAiMMLfmw4yAdqgEQGv8A
YCfi3ERH6BQtUESKVhwWgKionBmGSh5KPfesgaILwZGB3SCC4SHLlAgoTN0kU7pto0oDG8Ng
LRfgyQBK9AJAeBCAipQCCXDEsjJTZUwr5/5AIPCPEQ8FHevBFUpwLsSgVtbga7DAW9yDuhgN
IwUVWUtFa2Ceg7mGJ4qulUo9IUAp85KKd1S47AO1bpiDCKg9wmmPbxiof9/GHgAax2FGkaEk
IBd10WlFkvdQ9hfxKa+ECASULXgAZcF8ss9hhCDA9MooAMjplS0Y+5pzscIEGDDAwMC9WeZU
xmOkcfHHv5XFoZRneBhKDkTgGjAQkSYVKRTAUyyIADCQSqM9UAC4ftwp8kQ3ebGGXmyUNFDA
E2G0hQCGGD0AjFkxNZCcejKlxJl7UsEXG0xYKZhXbhZRQlaLBVDjQACWbELgQFKIoNpye3X0
gG2u7QPFVtCckFORC0EBVBJ3hAfJE7qJQM5cJIYxAJW4ROFYTPFBuVpHncU2JRQOBBELmjjQ
dgcDSRaBxRFxwkCnJCykwMKdeRIQ5xHe7DADnkIQQcMNeyK6AgmDMhEXoZBGKumklPpBihmV
ZqrpppmGAAA7
------------2E29447026B50
Content-ID: part2.333DB463.2F3A@medicineman.com
Content-Transfer-Encoding: base64
Content-Type: image/gif

R0lGODlhdwAOAMQAAP////Ly7+Xl39nZz8zMv7+/r7Kyn6Wlj5mZf42NcICAYHNzUGZmQFlZ
ME1NIEBAEDMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ACwAAAAAdwAOAAAF/yAhjgEABKKpruwqCioxtHRND+M4262AIDQCwsBrQY5ICJFwLNKOjhIA
wuAZGESniZE8VrUmJsR0zSKoYJP31zgKxGkVEjj91s50LffB6DMScQN9Jnhkf3FHdGIiTT50
PzAABgsLWVNHDzBoZAsMByUIXAx0AQcMCgQ0oi0BCacBBgSOhAgCs6FUQEJZpaepYa4JmhCo
BAoQUXBwl6lcDm0Kag0PxHUmx88QDZdIJ9QNDkotXA0jkc7ZCMtHjGNdAGdVAd/hRAXIewFd
yDDKTcwGkJVok4pKQAhMqgyA8GCgEgLQUh1bcIKhFBVckgBZ2BBAOHX/2CmLCA/NxIoNuf8U
AFAgwcJcuJI1WYdwAcM+H62RQ3Ng0xmKXOhQc9CH2i+MN/sQibcFAsgxzJYFJYRmaFGEx/AR
SWRCH4QD/qCyc/bjR8EqYtAwLVll6qVRZSMhtUP1S1Ca7Zo+QrMmboCMR3o6NXHPadiKCBNo
C6POGoCsVe45MKEYkNs2gCTVYrFqRcBtAO428Zo39GC2ADCT2SyrgE3ASTLBeZnAJkIBgQtQ
m7Fp3iZqB3RDgEGuVsAHBXpG4byPAe6vghHQtl26uA80x5ML/EigcvMZUo804JLKADWGWTah
BjAgHHrCSFIphrJjBWwvkjDlzDge4bLCCK01HzIztIcEAxc5MUAxfS4cpQUOLKBwFAoMgvHG
X6ctyIOENFDIAg5yxSHiiCTW4FaJKKao4ooruGIJizaEAAA7
------------2E29447026B50
Content-ID: part3.333DB463.2F3A@medicineman.com
Content-Transfer-Encoding: base64
Content-Type: image/gif

R0lGODlhlAAOAMQAAP////Ly7+Xl39nZz8zMv7+/r7Kyn6Wlj5mZf42NcICAYHNzUGZmQFlZ
ME1NIEBAEDMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ACwAAAAAlAAOAAAF/yAhjoQAnGiqAgRirHAcB4UboEMp56aM67DBATHwGY8BkQrCbEIQxxQC
wjglGMWojPBoPrKMpywMPZJhC6dCGx0wEicCcwlxMO6MF9vwPoUJbDACXQ0IDRAPN2cxi0aN
KAlMCZFigVtUcXMpTGUpAwoMUAgCLS8CCFClpw4QCnoEVwwHNwAGoLMrkYkAAV0viwJXCoAA
YQkIoSiwd7iPvJwnUw4Apy5wLKAJJjV6qDc1Bwp1o3IQAwsLRUzDIje9EA0Phy2Y5QBTDOVM
VQX7XQsAIjU4VEXFoTVxCCgSM6ALgy4FiiGKBwFOPyr/JHY6cbEHqSLlHlQxgCjMAwEkp/8N
YBKxgR0nIph0QRTACRNABzAJuImPxRx8SZgcKHIFkD0mN7zRgWIAFQJAZ9JA6TctTBV7RX1C
0KhiytZqqLQ6eNEFUCQFNc3lrFhTwSd4CssRWAmhnJ07RRbxrPcTE4CbyhAoOLSVFbwFxDaJ
CQPtTNkTTNxUAtxi8BxnXrXOkQuAbqYHAA4dWECQZMSeWiHXhZZCb92e9lADvocIwdrOhiMb
hACwKSsoZ2bfdE3vge3LlVBcHHBK3FZ7qVPnXPDAQBcFoGkXhH6TNQpx1/by61twNkQAF3kN
GGDg0MaAiIq8Ay7m0Iu0Ac6kHQQhYnpnaSGUGXT7oQcPNU0IkAbHb9H4xd1qNj1B0gMFOEdA
TsYRpp1qC0BxHQGE7VQdAWFElMI7Is1EHxQ5NUCAOGuYVGEdAHyooTO0wUPYc5oAkMYw9p1w
yDRrdVNbTFv9BaFNUDhHmEIzUbIhfHOQxISVAVjXxDUqDJCbAR1yRSUViihAyRe1NIEljmO6
yGOSvDBWESStdIbUCfw98WBiQQAyGxAxfHRCErSk0I4PORQKQxI9eMInoWwkkYUPpCh6xKGW
oDBbppx26umnoHaKV6iklmrqqSeEAAA7
------------2E29447026B50
Content-ID: part4.333DB463.2F3A@medicineman.com
Content-Transfer-Encoding: base64
Content-Type: image/gif

R0lGODlhfwAOAMQAAP////Ly7+Xl39nZz8zMv7+/r7Kyn6Wlj5mZf42NcICAYHNzUGZmQFlZ
ME1NIEBAEDMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ACwAAAAAfwAOAAAF/+BAjOQAnCeBGIBAmGgsz3RM3kJdq6yu36ScTycSMCDIJEOGgCyby6F0
lqwipijoKcGASavJK1Z2RHAbyAYjITOsAVrscYp0MO6MHtbNBhwJWHV4eWNkEGIESIAAPAkG
PHBOJwEHDAt6BFwMCg8IBSspCAEySGIxAwoMVwguoAIIVzyvDhAKBgOwJ69eJ6VMrAAGCICw
qAwFkwiqZSmKJ00Ph1paAWgNtGwFEJ1HDsFIowzepLUkowHRDQ9oKpKJEJEM70gMAkjITUIo
vjHOzHVJTCjYhuZQMwiLmjhp90TSAUkBkBgxCMBZtAIR+/QDA+jhEnsItbyLF+DdARMLIP+w
adCACpgr/gwiSRCAFkwIyGweTLht1DRJKcUcOdCkAYGHD0YNtAWBVy8Idu6YYFYxpDsk8Z4u
MgDV3gGXVqoC+ofQz6GRZhE5y5pVC1VmtJAsgJHowYJx5EydoKpIJNY4a9HVgqBvH0XDY2WW
LYOW6jueUX4uSVDrBJoCA/XEiKtxo14AA/v0laQNHuCyJwZCaOnyszM0NxOzApd25zNJbSUN
2Fbgobe4SOzCoNyUBphSXB9gVoQUQUG2csWU/tpaRrQFxGPXpqXgIcXHtyNLimMgGlQTDwvW
0bWtxnGDqgsSEKzyL27i8E7Qcvr0s8IHA2nHTGl2HVaIDC+csFtEFABE9AB7nWEhglgpFDaD
C144wNoYLmBR0igHTgGSArAckcA8FhaylopIaBbiizDS8AoetgAwgCXIxChViHdQF+OBIQAA
Ow==
------------2E29447026B50
Content-ID: part5.333DB463.2F3A@medicineman.com
Content-Transfer-Encoding: base64
Content-Type: image/gif

R0lGODlhywAOAMQAAP////Ly7+Xl39nZz8zMv7+/r7Kyn6Wlj5mZf42NcICAYHNzUGZmQFlZ
ME1NIEBAEDMzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ACwAAAAAywAOAAAF/+BAjOQAnCeBGIBAmGgsz7QsHGtQ7y2C7IERIEjgzQY+mHGZWjGfJxeJ
BJURGZCsliFDQLhebpVp0EIerCohu1tDAO5noGFejHfhu9FrZuvdCQx0EA0MCTIGhgB5T1hL
AQ8QBwQKZzpQAwxiNHFxTHQPCZUQP3qIiqY1fJqspp5uRXArCQYqLIwBBwwLaXCBDAoPCAVO
spcpWZcGxwYLDAfHBQrPOgI+J7nOCkWdbDixBgcyBVlpCxAO2Lq8TQS6CscHC+yyabm7abY9
pQSBCQIz+MjQZ+2HCnfALhGYd8APrBNeIvn4sojiHEIOIBwiJwxLujIQdDBIF0NAlgcLDv8A
PFHJAZ0GJxKYaRDEDx2XWUSwiVMJJgAICmTIhLCy2Y+LDTIe8pIxix0Ag7IEzYNUaUUuccg5
wPLgGEQ/KPLEYarFjklCkd7AyRJrlQqKeRpyCZBFAJZSbAFEKkD3kIxRWlgMsAQVgoGz4rBM
YpMpKIC73d4MDkmugAwsamXIHVKXTy42IAdAgoCE4ma6RMWywWK5QAIlX/tcXfvGc8PahACA
RAahLeE8ec6VUuylgTvClRSUgY0ikZkBmyum9OPChZ9cCBhIjHwio4FgMzDTEH6COMU458SI
CBCcVHlJqt+M2torbB/cWNnEf+z+Vd7Zs+Vx13s/NAXBAjCsgRL/STOsdNtEYoQhUAxxjMYL
HQhwJ90DjsXAx0oL/TAgfxDSxt8mX3Ex4l37BYBZFuJ4CFaKJu43oH+90RggRTI5Roc0htHQ
lF8yPoWaAVrFpBFIAOlSize5FZbhTtRpYZkMkw2HDgA9nvDjfi2xxEBpXHRZGDEUkaMWAQIU
kF4XM86m5mw8aWQibb5FCBdFgz1QQEPpGHgGgkqSNoMbW0XigA6RHFBAJAKM1kACkYwApZ8P
aljYAzWMklQWlvX555b7ubFAJV3lISqgADQkzCAAZJShTETGptkZCMC6Xxl+woqnjsBRpFta
DpjQUFRbtnBGDQak9QUMAzSFxgnRnsRCh4WDTKqRpmU8RcNQZ/TSbBbF0unHuOiYwAi65Y6m
EWMGMuBVRZlhk9ZQ5qo1yCipoPACtcJyxqmytR5BwLwAiGDwDgMwt0MZV9YQhMNwUMyJxSkw
x6bBK0GxMRMN97vDWQr4gEUCbhAl8spwJsvyyzDH/LI1rCiX8C4Ry5xKIgpgrPPPQKMQAgA7

------------2E29447026B50--
