From - Mon Jun 02 13:00:00 1997
X-Mozilla-Status: c000
Message-ID: <3389F638.70799264@user.com>
Date: Mon, 02 Jun 1997 13:00:00 -0800
From: Airius Partner <info@netscape.com>
Reply-To: info@netscape.com
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; uuencode=0; html=0
X-Mailer: Mozilla 4.05 (Win95; I)
MIME-Version: 1.0
To: Netscape Messenger User
Subject: Airius Memorandum
X-Priority: 3 (Normal)
Content-Type: multipart/related; boundary="------------3D11F2F98F1BE0120D838457"


--------------3D11F2F98F1BE0120D838457
Content-Type: text/html; charset=us-ascii
Content-Transfer-Encoding: 7bit

<HTML>
<BODY TEXT="#000000" BGCOLOR="#FFFFFF">
<IMG SRC="cid:part1.3389F638.3FAC59AA@user.com" HEIGHT=70 WIDTH=450 ALIGN=BOTTOM><FONT FACE="Arial,Helvetica">&nbsp;</FONT>
<TABLE CELLPADDING=10 WIDTH="425" >
<TR>
<TD COLSPAN="2"><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>TO: All Royal
Airways Sales and Reservations Specialists.&nbsp;</FONT></FONT>&nbsp;
<BR><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>FR: Airius Aircraft - Partner
Marketing Division.</FONT></FONT>&nbsp;
<BR>
<HR WIDTH="100%">&nbsp;
<BR><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>Airius Aircraft is pleased
to announce that 6 state-of-the-art, Airius 4000 intercontinental airliners
were delivered to the Royal maintenance hanger at San Francisco International
Airport. The 4000s feature several passenger comfort components requested
by Royal Airways:&nbsp;</FONT></FONT>&nbsp;</TD>
</TR>
</TABLE>

<TABLE WIDTH="425" >
<TR>
<TD ALIGN=RIGHT><IMG SRC="cid:part2.3389F638.3FAC59AA@user.com" HEIGHT=17 WIDTH=17><FONT FACE="Arial,Helvetica">&nbsp;</FONT>&nbsp;</TD>

<TD ALIGN=LEFT><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>Tan leather seats
in First Class and Business Class</FONT></FONT>&nbsp;</TD>
</TR>

<TR>
<TD ALIGN=RIGHT><IMG SRC="cid:part2.3389F638.3FAC59AA@user.com" HEIGHT=17 WIDTH=17><FONT FACE="Arial,Helvetica">&nbsp;</FONT>&nbsp;</TD>

<TD ALIGN=LEFT><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>Full feature
communication panels in Business Class</FONT></FONT>&nbsp;</TD>
</TR>

<TR>
<TD ALIGN=RIGHT><IMG SRC="cid:part2.3389F638.3FAC59AA@user.com" HEIGHT=17 WIDTH=17><FONT FACE="Arial,Helvetica">&nbsp;</FONT>&nbsp;</TD>

<TD ALIGN=LEFT><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>On-board food
prep galley for First and Business class meals</FONT></FONT>&nbsp;</TD>
</TR>
</TABLE>

<TABLE CELLPADDING=10 WIDTH="425" >
<TR>
<TD COLSPAN="2">
<TABLE BORDER >
<TR>
<TD ALIGN=CENTER WIDTH="100"><B><FONT FACE="Arial,Helvetica">plane</FONT></B>&nbsp;</TD>

<TD ALIGN=CENTER WIDTH="100"><B><FONT FACE="Arial,Helvetica">class</FONT></B>&nbsp;</TD>

<TD ALIGN=CENTER WIDTH="100"><B><FONT FACE="Arial,Helvetica">capacity</FONT></B>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">1 - "Enterprise"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-B</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">350</FONT>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">2 - "Synergy"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-B</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">350</FONT>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">3 - "Henry V"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-V</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">296</FONT>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">4 - "William"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-V</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">295</FONT>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">5 - "Senator"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-B</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">352</FONT>&nbsp;</TD>
</TR>

<TR>
<TD><FONT FACE="Arial,Helvetica">6 - "Mercury"</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">4000-D</FONT>&nbsp;</TD>

<TD><FONT FACE="Arial,Helvetica">320</FONT>&nbsp;</TD>
</TR>
</TABLE>
<FONT FACE="Arial,Helvetica"><FONT SIZE=-1>For a full description of these
and additional features of the 4000 aircraft, please visit our partner
section of the <A HREF="http://home.netscape.com/comprod/at_work/vip/index.html">Airius
4000 intranet.</A>&nbsp;</FONT></FONT>&nbsp;

<P><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>We wish you continued success
in the safe, comfortable and rapid delivery of your passengers to their
many destinations!&nbsp;</FONT></FONT>&nbsp;

<P><I><FONT FACE="Arial,Helvetica"><FONT SIZE=-1>Airius Aircraft</FONT></FONT></I>&nbsp;
<BR><FONT FACE="Arial,Helvetica"><FONT SIZE=-1><I><A HREF="mailto:info@netscape.com">Partner
Marketing Division</A></I>&nbsp;</FONT></FONT>&nbsp;</TD>
</TR>
</TABLE>

</BODY>
</HTML>

--------------3D11F2F98F1BE0120D838457
Content-Type: image/gif
Content-ID: <part1.3389F638.3FAC59AA@user.com>
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="Drafts?id=333C2585.2270@medicineman.com&number=6&part=1.2"

R0lGODlhwgFGAPcAAP////7+//7+/v39/vz8/vz8/fv7/fr6/fr6/Pn5/Pj4/Pj4+/f3+/b2
+/b2+vX1+vT0+vT0+fPz+fLy+fLy+PHx+PDw+PDw9+/v9+/v7+7u9+7u9u3t9uzs9uzs9evr
9erq9erq9Onp9Ojo9Ojo8+fn8+bm8uXl8uTk8uTk8ePj8eLi8eLi8OHh8ODg8ODg79/f79/f
397e797e7t3d7tzc7dvb7dra7dra7NnZ7NjY7NfX69bW69bW6tXV6tTU6tTU6dPT6dLS6dLS
6NHR6NDQ6NDQ58/P58/Pz87O5s3N5szM5szM5cvL5crK5crK5MnJ5MjI5MfH48bG48bG4sXF
4sTE4sTE4cPD4cLC4cLC4MHB4MDA37+/37+/v76+376+3r293ru73bq63bq63Lm53Li427e3
27a227a22rW12rS02rS02bOz2bKy2bKy2LGx2LCw2LCw16+v16+vr66u166u1q2t1qys1qys
1aur1aqq1aqq1Kmp1Kio1Kio06en06am06am0qWl0qSk0qSk0aOj0aKi0aKi0KGh0KCg0KCg
z5+fz5+fn56ez56ezp2dzpyczpyczZubzZqazZqazJmZzI+Pj39/f3BwcGBgYFBQUEBAQDAw
MCAgIBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAwgFGAAAI/wAvCRxIsKDBgwgTKlzIsKHD
hxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyhTqlzJsqXLlzBjypxJs6bNmzhz6tzJs6fP
n0CDCj0JoKjRo0iTKl3KtKnTp1CjSp1KtarVq1izat3KtavXr2DDih1LtqzZs2jTql3Ltq3b
t3Djyp1Lt67du3jz6t3Lt6/fv4ADCx5MuLDhrQZkNPFBgeyDHFBwMAhwuLLly5j1MiACyJLn
IGIVHPFsqRCLAZlTq17NGmyFM5BIHxFbogxpQzYMtN7Nu7fvo69jV0p0g7Ztz4I0/F7OvLnh
B00IWZoEaIZYCFBIA4LgvLv373YHWP9oM736WBWCPG8Hz769e7QXqBiq42LsAA9YIOl58L6/
//8ABijggAQWaOCBCCao4ILfKWDDFGeE0YJuU8HQBRYdNDVBDUJIoBQDNGAxhxYgFICUATeQ
IUUCTolnAotMiSBGJHpYBxUBF8DgRBltiOFDBagxKCSBAlRgRWyeVWKIHXDAoUKLJaxBWhcc
KJVAdJ6VUcJRDBTxB2mWAILBUTLoMYklinRhAVMLhOFZJFFMltQEapB2hglOGdCDHmCSlogN
QwYKYARKGNJnn1J4yJQNZ5ImhghJYYAFI6T1AWhRKuzRKGl3VGAUE4qQ5kgZyin1gBSGembI
EyYepUEZjjj/+gFTA9iQ6qGWMAKFoLy6Z0MepDHixh+belZDU0sg6RkiNiJFQ6yywcgEtGDe
AcMBAEQQxa2W2OFBkEmpsEi1NoALgGhgOkLDUgEwYMWhibBRxRNH0EBhr/g2t0AQX3qmxpYS
ZBFsGKUmlYAP/XpGCBANKCUEaZG0kSEDUBhayRxJ8CBGGccCkAARxfrxA1MntLHpJEYkpQSY
jGAxplIQnAGmIVWIYG6+ODMnQROPvBlFYwA0IAVpf9AA45x89FnGvUc9UAXROQwAgRSUJqIF
0M7uUQmYTTQ1NGmQAHE0AAfswCdpebycVAVSJOKZJEQwnfPcvyWARaU7LGDUCmyQ/5bGzUed
cAiY/wIOwAdikOZGAgR83QcPTBEBZiT/LiUADXOQpofRRw3AQiFgEtLE2Eep4DaaW6hN9+q8
DbBFo4KAZtQAbqo3hOFFVQA6aUww5YIbb1KRABcKv9BUDoP4mQO2Sg2QhuY5JDXDIJQQLgIB
S81AmiKps+59axJU7Bklshc1ARiUetbGCgIsBYIYSE5yxpZKGXCk+kpQAboekDYluWeTQAN3
lKKBMKTPElJo2FFycDYw7WopHOgCmCZxqe9ZEDM72F4VLmAUCkQhEmDqgqKSIoLjeAYSMFhK
CeawKUH0wTN2sBdT2gUG0sxhQkqhwR3AtAjjGWUBO3hhn//mkMKkHAAGO+wTHIp4wSYWRoc2
9BQAArCALRxqNkm5D3lIMwk4qM4oRBgXrgoBuaYYIAhCtMQXPiS+YFGpgx+cTiICkb4rcBAp
O+sZHpiwBzC14VtODGRgvkAaPOSAQhyQA66weJQC8OCAnulD3vA4hmL16Qe4M4oC6uSZP+gg
KSVQAwjBFAgUoGYAoZzSBwzoGUweJQAjkJkl9ACoEXDSM50SpC73cgAfpHELQXKBH7YmiDIk
zzOMBIAAHiDBQ6mBAUdBABFO5wg8QPIQVJjAUz7QGc9oQXUJkEKoDsUHaDYACNKxBNwA4IBu
WuIErmIlJNpAAqPYQBDVs8QjmjD/wl1eBhOc4IRROJEJpGRCoFPZBEGLggRONAIrdHAoUxaK
FgfEAUxOAAAFmmkJKGDACAnrWlEGoIKkVYIRgjhdJB7oMRrAgTRfyIEYTueZM5BOKTujaccA
YAAdpCdXYJjD1jwzCBvkQEqeqcOWanUreAYgAVBI3yTG0M8EACF+d2iBPzPjCVCAAglFwcRD
j9IITEwlBl79RFFigAkvYOUTnohBBsyaFFAg9CwkGJx24NAo3PCUBg1sQwoAUAIyNOoMHpCl
Z6oAgAWANJ+D+OQJirVEqJCgDcr6pAaOkMY51OACicOVJeAkpwccgaZOuEEXdlcJOKwrKRw4
JnWatdXD/yABFJsAxSWUkoEMNCUGXvDtUS6B268qJQYMDe5RkAsAL7i1KHYFACdAoZToFiUD
YF2rF5jLFRvQtE9muMApxyNaz0ABNWQoryUq0QVPSWAKxRJCVC6rrEMxggqe2sAtJwiHEBzl
ApMSrSGiEAEAEABxkPgDFZRwhkbts5+1LQxxvYBb6AqUE574xCWmCwBMgMILHM4EKDrxiewW
ZROfoINumwsKs474q5r4BInd+mIkkDjDMZiuV716V6NEd7qfaDEAGmHXFXMlr32iTg4oc5R3
4coOLQjSD/yAK0ioAZ5F4cAW8vmILVQJKg8gArfABgZAFoUKh5rDa48SPjGCif8SLitKA4hA
rT4ZQgr8iXBlcguArlpYurgFMXU9LGgAjJitzy3KJziBVoFS2MWgyASFCwoKTRg60l5o66MN
fWHq1rXTje5zJ6Tria4k4Aju7IMQ8nyiIxSrDTK4WRLApCQrgOBmK6xeHzIklQSI4WR7wFBS
TiDLRITBBTctCgmO6Zk5+KDARhlBGUZJGiVBQYp6rsyIBU3jTheFw4QOMSg8QYejUFgTXggy
i13saCH7GKGX6KqQf+xppNCb0/gOSwVsEAQRyA0pA8DADozgAr01zwNHaMINNtCqpXwgBP9+
ygBQwIQm2ECbTEnABzCQ7M59IAhKgAE0lVIBIrxBEpX/6IMVUpDJbAdGxTuONL45DOgOf5jm
dOjqWAEg4pjTYdPR3bQXwBpdtG4C6N7+dM2jG10kJNrlUM+MiMGagRHP3NPgBgUdOkFdglb9
riQuioolPW+BVj0TVd8Evh+tYnbX3Au7fffSBdqJUYe9rVHPe2XCXhSuf73mb08rdTUx4hRf
t8IAqHonkF6UGM843xmertsbsehNqF3uHI4ukae7W3fr/fO+iQF3AeB04Val9EnJwNOT4omd
OwW4owe97Juo3Nnb/vZsibnud8/73vv+98APvvCHT/ziG//4yE++8pfP/OY7//nQj/7zcU/9
6lv/+tjPvvaPm+jtahcpmXa9/1QyEPvEO9fE209/ZrzQiYNKNxOLz3EmCsrQxWtC/FABblJA
jIlN0F/9AFgZjQBWAlVQ4Vdul9dhbhUDY4UEpidXzcVcwGV6ayVcmfZtRoF+AbiBgBEDCShW
eHdXeGcU88dofcYJSJAJjbAJoscJEdVcZuUJKFgUFyhdHUZRHJiDfcF+5QYAMeAJc+VWIvh0
AkUHu1VqAKAJcad/jhaD5kZXAiVWOjiFfjFq0uVWIWgUI4iBF4hQGcAJneBbmoAJpdaFT4iB
W0iFakgX9BeFY9UICGgUjfBQX2iDRmiDQwYAl9BWZjVqZmgUF1iHabiGhPgW/Td/nEZQ8vd/
GeAJmP/QCeVWgsiFUP53dBnQfmVoVj3mBTIIiQqIh4UYimyBBBr4fUehetzlfeAngRQoiq5I
hcD1XE5XijToXKt3Xc7lW7HIFGWFf4DoXOVnbrdoFMAFVvrHfUPHFKRofq2YXNkFjK/och4G
CsjFdT12FOMWUEpBYaDwUD23FJnwCZjwCf9nb57AdcNIel5FizZXah62FB7GCZ9gaUqhjRQ2
jNNValXnedFYW9PYCPt4jT5GV9voVZbGdfWGFO3Hc1ZYV5hQdQSJFJfAdRF5FNOYaQlpkdRF
ZM0oXe2Gj14VAzBXkf1oFWx1CR3JFOR3XMyFBC3pW6q3FKIHiH8Rj5qgYtr/WF3oRosUhmFf
l5EDaXNL0WK35YvSpQk5mRQetgljCJRhRV33WI8fKZXdeFD8WJJV8YVwR49MIYEwqBR0QI+d
QI9AqIefUH50YHl08IUA9YUYRledQFcqFhce9ogHlZTmiIPm1mLdyJdDaVbvWF1e1ZB1VVag
0JEeRmQiBo9Q+WFSyWL4GFDwV5dYiRVeQH8NaGLJiIdNSIPc1YiJtwmlFgNWGJdxdxRqlwGS
BpjPdXTNxQl0tQmE2RaENmIAJZDQRZKA+GEjBptOaWiA+ZtE2Y1gOWJc14NI8Y5w9ZvvSGG0
aI+OmRQB9Yi8qZuVGRWOaBR0gAmYsFuZcAk3yYli/9V6F5gJaWliYWiEnJABZZV4jDabNviF
GaB2JthnjdeeMYCUdEld64iX2GidkMl5gSmdlqaf1eViupkJnuBc5KgU70h4zDloaqUUsgkA
KvacnEBhanWV1ykVDRWGAHB5AvVQf9iZaleDPEcHmYAEbSVpQ7ZbnRB7l8CUAqVQl5eWPohu
ZqUJObaf0qVW/uljO1aQGMmiv7l5xHmgANCgSTGW34aEyUldtxWhoPAJRpluJMaVSKGNFcah
HSoVl1BQsIkJBaWiY8iZX+mIKqid/Wehj3hiY9gJp5mBX5iCPAdWa9p/SBkD4th63gF7grGZ
XzoWNVijvvVQRaiJXKiox2rongKVY2a3oF7QCLNJhzr6iXHlg1upeuzHjoOKlbDpghZqeYCp
CZtgVvAHAO1XnvD3dNnZZ7ulokZRYg3Zf5tQbqFKeoSJorj5qdepiqRnYp4KiMHoFHTgei6J
iynpq8w6FxDYrNCKMwEBADs=
--------------3D11F2F98F1BE0120D838457
Content-Type: image/gif
Content-ID: <part2.3389F638.3FAC59AA@user.com>
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="Drafts?id=333C2585.2270@medicineman.com&number=6&part=1.3"

R0lGODlhEQARAMQAAP////7+/vz8/Pr6+vj4+Pf39/Pz8+np6eLi4t/f397e3t3d3cXFxbGx
saioqKampqWlpZnMzJSUlHBwcF9fX1tbW1paWj8/PzOZmSkpKSMjIyIiIgBmZgAAAAAAAAAA
ACwAAAAAEQARAAAFi2AkjqSIHMYQlCzXMIkhiFht1xw3Scwx0Ddb7jJpIAjAICaXoTgUhWQw
p6lAFtGIEsfZWK7Z7bL7xUpvOS/4LCSvI7m4nFNdz+/NZwHRmFwyGhuCGxoZREYEBwwSExQW
j5AUOz0DBgkMDQ4PEJwQDw4vMQKVBwgKC6ipCicpAQGjBAWys7IEAwIBACEAOw==
--------------3D11F2F98F1BE0120D838457--

